title: Ruby developer roadmap
author: Roonyx team
email: it@roonyx.tech
description: >-
  Мы составили карту навыков и компетенций Ruby разработчика, которую можно использовать для развития себя и команды.
  Попробуйте приложить её и к себе!
baseurl: '/ruby-developer'
url: ''
twitter_username: RoonyxTech
#github_username: Roonyx
facebook_username: RoonyxTech
#linkedin_username: Roonyx
instagram_username: roonyx_tech

# Build settings
theme: "just-the-docs"
markdown: kramdown
kramdown:
  parse_block_html: true
exclude: ['README.md', 'LICENSE.md', 'Gemfile.lock', 'Gemfile', '.idea']
plugins:
  - jekyll-feed

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

footer_content: "Distributed by an <a href=\"https://github.com/roonyx/ruby-developer-roadmap/blob/master/LICENSE.md\">License Attribution-ShareAlike 4.0.</a>"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on Github."
gh_edit_repository: "https://github.com/roonyx/ruby-developer-roadmap" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
